- name: Download Configurations Auto Updater
  get_url:
    url: https://github.com/Ferlab-Ste-Justine/configurations-auto-updater/releases/download/v0.2.0/configurations-auto-updater_0.2.0_linux_amd64.tar.gz
    dest: /opt/configurations-auto-updater.tar.gz
    mode: 0555
- name: Get sha256 Sum of Configurations Auto Updater Download
  stat:
    path: /opt/configurations-auto-updater.tar.gz
    checksum_algorithm: sha256
    get_checksum: yes
  register: configurations_auto_updater_tar_stat
- name: Verify Configurations Auto Updater Checksum Match Expected Value
  fail:
    msg: "Failure: configurations auto updater download doesn't have expected checksum."
  when: configurations_auto_updater_tar_stat.stat.checksum != '673cbd3ad21065f5bec6e8d77b3c5560264708dbe39a04cf2af809dae6c40ac3'
- name: Create Configurations Auto Updater Untar Directory
  ansible.builtin.file:
    path: /opt/configurations-auto-updater
    state: directory
- name: Extract Configurations Auto Updater From Tar Archive
  ansible.builtin.unarchive:
    src: /opt/configurations-auto-updater.tar.gz
    dest: /opt/configurations-auto-updater
    remote_src: yes
- name: Copy Configurations Auto Updater Binary
  ansible.builtin.copy:
    src: /opt/configurations-auto-updater/configurations-auto-updater
    dest: /usr/local/bin/configurations-auto-updater
    owner: root
    group: root
    mode: '0555'
    remote_src: yes
- name: Delete Configurations Auto Updater Downloaded Artifact
  ansible.builtin.file:
    path: /opt/configurations-auto-updater.tar.gz
    state: absent
- name: Delete Configurations Auto Updater Untar Directory
  ansible.builtin.file:
    path: /opt/configurations-auto-updater
    state: absent