- name: Create Opensearch User
  ansible.builtin.user:
    name: opensearch
    system: yes
    password_lock: yes
- name: Install Opensearch Automation Packages
  ansible.builtin.apt:
    pkg: 
      - curl
      - jq
    update_cache: yes
- name: Download Opensearch
  get_url:
    url: https://artifacts.opensearch.org/releases/bundle/opensearch/2.2.1/opensearch-2.2.1-linux-x64.tar.gz
    dest: /opt/opensearch.tar.gz
    mode: 0555
- name: Get sha256 Sum of Opensearch Download
  stat:
    path: /opt/opensearch.tar.gz
    checksum_algorithm: sha256
    get_checksum: yes
  register: opensearch_tar_stat
- name: Verify Opensearch Checksum Match Expected Value
  fail:
    msg: "Failure: opensearch download doesn't have expected checksum."
  when: opensearch_tar_stat.stat.checksum != '259526b62b099f0bc3b8c5723c53332a5127cdace60c89ea1404daed916f7207'
- name: Extract Opensearch From Tar Archive
  ansible.builtin.unarchive:
    src: /opt/opensearch.tar.gz
    dest: /opt
    remote_src: yes
- name: Copy Opensearch Directory
  ansible.builtin.copy:
    src: /opt/opensearch-2.2.1/
    dest: /opt/opensearch
    owner: opensearch
    group: opensearch
    remote_src: yes
- name: Delete Opensearch Copied Opensearch Directory
  ansible.builtin.file:
    path: /opt/opensearch-2.2.1
    state: absent
- name: Delete Opensearch Downloaded Artifact
  ansible.builtin.file:
    path: /opt/opensearch.tar.gz
    state: absent
- name: Download Opensearch Prometheus Plugin
  get_url:
    url: https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.1.0/prometheus-exporter-2.2.1.0.zip
    dest: /opt/prometheus-exporter-2.2.1.0.zip
    mode: 0555
- name: Get sha256 Sum of Opensearch Prometheus Plugin Download
  stat:
    path: /opt/prometheus-exporter-2.2.1.0.zip
    checksum_algorithm: sha256
    get_checksum: yes
  register: opensearch_prometheus_plugin_tar_stat
- name: Verify Opensearch Prometheus Plugin Checksum Match Expected Value
  fail:
    msg: "Failure: opensearch prometheus plugin download doesn't have expected checksum."
  when: opensearch_prometheus_plugin_tar_stat.stat.checksum != '34c4ac68fcc4c1fe237e7986fde73cf4a46a9870a1591b34d59f1c0e77341b86'
- name: Install Opensearch Prometheus Plugin
  ansible.builtin.shell: /opt/opensearch/bin/opensearch-plugin install -b file:/opt/prometheus-exporter-2.2.1.0.zip
- name: Delete Opensearch Prometheus Plugin Downloaded Artifact
  ansible.builtin.file:
    path: /opt/prometheus-exporter-2.2.1.0.zip
    state: absent