- name: Setup Chrony
  hosts: all
  roles:
    - { role: ../../../ansible-roles/chrony, become: true }
- name: Setup Fluentd
  hosts: all
  roles:
    - { role: ../../../ansible-roles/fluentd, become: true }
- name: Setup Prometheus Node Exporter
  hosts: all
  roles:
    - { role: ../../../ansible-roles/prometheus-node-exporter, become: true }
- name: Setup Etcd
  hosts: all
  roles:
    - { role: ../../../ansible-roles/etcd, become: true }